# Rime default settings
# encoding: utf-8

config_version: "2023-12-18"

schema_list:
  - schema: luna_pinyin # 朙月拼音
  - schema: lufs_flypy # 小鹤双拼
  - schema: lufs_mspy # 微软双拼
  - schema: lufs_dpy # 自然码双拼
  - schema: lufs_pyjj # 拼音加加双拼

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - traditionalization
    - emoji_suggestion
  fold_options: true
  abbreviate_options: true
  option_list_separator: "/"

menu:
  page_size: 5

punctuator:
  full_shape:
    __include: punctuation/symbols:/punctuator/full_shape
  half_shape:
    __include: punctuation/symbols:/punctuator/half_shape

recognizer:
  patterns:
    # 禁止部分输入的自动上屏
    camel: "[a-z]+[A-Z].*$" # 驼峰命名
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$" # email 地址
    html: "^<[a-z]+>$" # HTML TAG
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$" # 大写开头
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$" # URL 输入

    # 响应功能
    punct: "^/([0-9]0?|[A-Za-z]+)$" # 响应 lufs_symbols.yaml 内的输入
    unicode: "^U[a-f0-9]+" # 响应 Unicode

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
